# Dependencies
markdown:         redcarpet
highlighter:      pygments 

# Permalinks
permalink:       "/:title"

# Setup
title:            Disaster Area
tagline:          'Adventures in Software Development'
description:      'Follow me on Twitter: <a href="https://twitter.com/vivekprahlad" target="_blank">@vivekprahlad</a>.'
url:              http://blog.vivekprahlad.com
baseurl:          '/'
paginate:         5

author:
  name:           'Vivek Prahlad'
  url:            https://twitter.com/vivekprahlad

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
